### ISSUE TITLE
Improve regexes?

### ISSUE THREAD

**Issue by Myzel394** [crisp-oss/email-reply-parser#22]
Hi I noticed that your regexes use "{0,1}" which is the equivalent to "?" - Is there any reason on why to use this notation instead of a "?"?

**Comment by baptistejamin** [comment]
There are many regexes to maintain. A such notations is computationally the same, and meanwhile makes all those regexes easier to maintain Sent from my iPhoneOn 15 Apr 2023, at 15:43, Myzel394 ***@***.***> wrote:﻿
Hi I noticed that your regexes use "{0,1}" which is the equivalent to "?" - Is there any reason on why to use this notation instead of a "?"?
